prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 4000m
        memory: 8000Mi
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

prometheus-node-exporter:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 2000m
      memory: 1000Mi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 1000m
        memory: 1000Mi

  config:
    global:
      resolve_timeout: 5m
    receivers:
    - name: webhook
      webhook_configs:
      - url: "http://orca.rca:5000/v1/ingestor/prometheus"
    route:
      group_by: ["job"]
      group_interval: 30s
      group_wait: 30s
      receiver: "webhook"
      repeat_interval: 12h
      routes: []

grafana:
  sidecar:
    dashboards:
      searchNamespace: ALL
