prometheus:
  mappings:
    - name: KubePodNotReady
      source_mapping:
        kind: pod
        properties:
          name: pod
          namespace: namespace
    - name: KubePodCrashLooping
      source_mapping:
        kind: pod
        properties:
          name: pod
          namespace: namespace
    - name: KubeContainerWaiting
      source_mapping:
        kind: pod
        properties:
          name: pod
          namespace: namespace
    - name: KubeDeploymentReplicasMismatch
      source_mapping:
        kind: deployment
        properties:
          name: deployment
          namespace: namespace
    - name: KubeStatefulSetReplicasMismatch
      source_mapping:
        kind: stateful_set
        properties:
          name: statefulset
          namespace: namespace
    - name: CPUThrottlingHigh
      source_mapping:
        kind: pod
        properties:
          name: pod
          namespace: namespace
    - name: KubeAPILatencyHigh
      source_mapping:
        kind: cluster
        properties: {}
    - name: KubeHpaMaxedOut
      source_mapping:
        kind: horizontal_pod_autoscaler
        properties:
          name: hpa
          namespace: namespace
    - name: KubeHpaReplicasMismatch
      source_mapping:
        kind: horizontal_pod_autoscaler
        properties:
          name: hpa
          namespace: namespace
falco:
  blacklist_values:
    - '<NA>'
  mappings:
    - name: "Launch Sensitive Mount Container"
      source_mapping:
        kind: pod
        properties:
          name: k8s.pod.name
          namespace: k8s.ns.name
    - name: "Launch Privileged Container"
      source_mapping:
        kind: pod
        properties:
          name: k8s.pod.name
          namespace: k8s.ns.name
    - name: "Create Sensitive Mount Pod"
      source_mapping:
        kind: pod
        properties:
          name: ka.resp.name
          namespace: ka.target.namespace
    - name: "Create Privileged Pod"
      source_mapping:
        kind: pod
        properties:
          name: ka.resp.name
          namespace: ka.target.namespace
    - name: "Terminal shell in container"
      source_mapping:
        kind: pod
        properties:
          name: k8s.pod.name
          namespace: k8s.ns.name
    - name: "Detect outbound connections to common miner pool ports"
      source_mapping:
        kind: pod
        properties:
          name: k8s.pod.name
          namespace: k8s.ns.name
elastalert:
  mappings:
    - name: "Application error"
      source_mapping:
        kind: pod
        properties:
          name: pod_name
          namespace: namespace_name
